services:
  postgres:
    image: postgres:13.2
    restart: always
    container_name: postgres_stage
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: popug_ates_rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8888:8888"



volumes:
  postgres_data_stage:
