services:
#  postgres:
#    image: postgres:13.2
#    restart: always
#    container_name: postgres_stage
#    volumes:
#      - postgres_data_stage:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env
#

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
